name: Healthcheck

on:
  push:
    branches:
        - main

jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Healthcheck
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-divine-sea-2558.fly.dev
          max-attempts: 3
      - name: Discord success notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        if: success()
        with:
          args: 'Healthcheck to https://fs-part11-my-app.fly.dev passed'
      - name: Discord error notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        if: failure()
        with:
          args: 'Healthcheck to https://fs-part11-my-app.fly.dev failed'