name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SECRET: ${{ secrets.SECRET }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install && cd frontend && npm install
      - name: Check backend style
        run: npm run lint
      - name: Check frontend style
        working-directory: ./frontend
        run: npm run lint
      - name: Test backend
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
        run: npm run test
      - name: Test frontend
        working-directory: ./frontend
        run: npm run test