name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SECRET: ${{ secrets.SECRET }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install && cd frontend && npm install
      - name: Check backend style
        run: npm run lint
      - name: Check frontend style
        working-directory: ./frontend
        run: npm run lint
      - name: Test backend
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
        run: npm run test
      - name: Test frontend
        working-directory: ./frontend
        run: npm run test
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
      - name: Discord error notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        if : ${{ github.event_name == 'push' && failure() }}
        with:
          args: 'Build failed. Commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.committer.username }} broke the code.'